### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by zkan** [prontotools/zendesk-tickets-machine#1]
We need to protect our data and allow only Pronto agents to see them.

**Exit Criteria**

- Upgrade Django to 1.11 alpha 1. `pip install --pre django`
- Have a login page. Use LoginView. - https://docs.djangoproject.com/en/dev/topics/auth/default/#django.contrib.auth.views.LoginView
- After login, it should redirect to the main page.
- Login is required on all pages.

**Comment by zkan** [comment]
LoginView is introduced in Django 1.11. - https://docs.djangoproject.com/en/dev/topics/auth/default/#django.contrib.auth.views.LoginView

**Comment by zkan** [comment]
Let's get the alpha for 1.11. -  https://www.djangoproject.com/download/

**Comment by zkan** [comment]
Django 1.11 will be a LTS version. We should upgrade all projects to that version. Since ZTM is a small project, we should try it.

**Comment by nattyait** [comment]
pip install Django==1.11a1

right?

**Comment by zkan** [comment]
Not sure. Never try it. If it works, it works. LOL
          
            
            On Jan 23 2017, at 3:54 pm, Nattanicha <notifications@github.com> wrote:
            
            
              pip install Django==1.11a1
right?

**Comment by nattyait** [comment]
ok I see. I'm reading on it. I can't use `pip install --pre django` but the command above is ok.

**Comment by zkan** [comment]
Need to fix when we log in on this page https://ztm.prontomarketing.com/login/, it goes to https://ztm.prontomarketing.com/accounts/profile/.

**Expect**
* It should go to https://ztm.prontomarketing.com/.

**Note**
* To fix this, add this setting `LOGIN_REDIRECT_URL` to our base settings to override the default one. See https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-LOGIN_REDIRECT_URL
