### ISSUE TITLE
Be able to choose agent for "created by"

### ISSUE THREAD

**Issue by nattyait** [prontotools/zendesk-tickets-machine#30]
As a newsletter and WP team, I want to be able to choose agent to create first comment when create ticket. So that it will not be confused. See the screenshot below.

<img width="1436" alt="screen shot 2560-01-31 at 2 56 19 pm" src="https://cloud.githubusercontent.com/assets/704794/22465969/c3643820-e7f0-11e6-893e-1f144aabf212.png">

**Exit Criteria**
* When create ticket, add "created_by" field to choose agent

**Comment by zkan** [comment]
We need to create a Zendesk ticket like this.

<img width="1436" alt="screen shot 2560-01-31 at 2 56 19 pm" src="https://cloud.githubusercontent.com/assets/704794/22465969/c3643820-e7f0-11e6-893e-1f144aabf212.png">
