### ISSUE TITLE
Edit Data in Column at the Same Time

### ISSUE THREAD

**Issue by zkan** [prontotools/zendesk-tickets-machine#5]
As a newsletter team, I wanna edit the data in a column together at the same time, so that I don't need to edit each ticket one by one.

**Exit Criteria**

- Be able to edit data in a column at the same time.

**Note**

- DataTables example: https://editor.datatables.net/examples/advanced/multiItem.html

**Comment by nattyait** [comment]
@zkan  If we wanna use this js lib, we need to pay ah... https://editor.datatables.net/purchase/index
should we pay? 

Last time, I found this http://django-datatable-view.appspot.com/x-editable-columns/ but it's not exactly like editor.datatables.

**Comment by zkan** [comment]
Let me check first.

**Comment by nattyait** [comment]
![img_0083](https://cloud.githubusercontent.com/assets/832101/22635135/42f8d96c-ec63-11e6-8f4f-7d66b4dad8d7.PNG)

**Comment by zkan** [comment]
Got a defect. After add a new ticket, the edit rows form is gone.

**Comment by zkan** [comment]
Only tags works on the edit rows form.
